name: PHP Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.1' ]
    services:
      mysql:
        image: mysql:8.4
        env:
          #MYSQL_ALLOW_EMPTY_PASSWORD: false
          #MYSQL_ROOT_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: oodb
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost -P 3306 -uroot -ppassword"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: oodb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, pdo, pdo_mysql, pdo_pgsql, sqlite3
          coverage: xdebug

      - name: Wait for databases
        run: |
          timeout 60s bash -c "until mysql -hlocalhost -P3306 -uroot -e 'SELECT 1'; do sleep 1; done"

      - run: touch /tmp/oodb.db
      - run: PGPASSWORD=password psql template1 -hlocalhost -c 'CREATE EXTENSION "uuid-ossp";' -U postgres
      - run: php replica2.php onlyphp
      - run: cp rb.php testing/cli/testcontainer/rb.php
      - run: cd testing/cli

      - name: Run tests
        run: php runtests.php
        working-directory: testing/cli
        env:
          PGUSER: postgres
          PGPORT: 5432
          PGHOST: localhost
          MYSQL_HOST: localhost
          MYSQL_USER: root
          MYSQL_PASS: password
          MYSQL_DB: oodb
          XDEBUG_MODE: coverage
