name: PHP Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.1' ]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: oodb
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost -P 3306 -uroot -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: oodb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, pdo, pdo_mysql, pdo_pgsql, sqlite3
          coverage: xdebug

      - name: Wait for databases
        run: |
          timeout 60s bash -c "until mysql -h127.0.0.1 -P3306 -uroot -proot -e 'SELECT 1'; do sleep 1; done"
          timeout 60s bash -c "until PGPASSWORD=postgres psql -h127.0.0.1 -U postgres -d oodb -c 'SELECT 1'; do sleep 1; done"

      - name: Create SQLite DB
        run: touch /tmp/oodb.db

      #      - name: Setup PostgreSQL extension
      #        run: |
      #          PGPASSWORD=postgres psql -h127.0.0.1 -U postgres -d template1 -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'

      - name: Run PHP setup
        run: |
          touch /tmp/oodb.db
          mysql -e 'create database oodb;'
          psql template1 -c 'CREATE EXTENSION "uuid-ossp";' -U postgres
          psql -c 'create database oodb;' -U postgres
          php replica2.php onlyphp
          cp rb.php testing/cli/testcontainer/rb.php
          cd testing/cli

      - name: Run tests
        run: php runtests.php
        working-directory: testing/cli
        env:
          PGUSER: postgres
          PGPORT: 5432
          PGHOST: 127.0.0.1
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASS: root
          MYSQL_DB: oodb
          XDEBUG_MODE: coverage
